version: '3.3'

services:
  lightfeather-backend:
    image: lightfeather-backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8080:8080"

  lightfeather-frontend:
    image: lightfeather-frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3000:3000"
